query getEpisodes($page: Int, $name: String) {
  episodes(page: $page, filter: { name: $name }) {
    info {
      count
      pages
      next
      prev
    }
    results {
      id
      name
      characters {
        id
        name
        status
        image
        gender
        type
        species
        location {
          id
          name
        }
      }
    }
  }
}
